### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by aksr** [jhawthorn/fzy#56] opened 2017-10-13 16:04 UTC
1.` ls | fzy`
2. type anything (*more than a few words*)
3. C-a
4. C-w (*multiple times until everything is deleted; cursor goes suddenly right*)
5. Space (*maybe multiple times*)
6. **Segmentation fault**

**Comment by jhawthorn** [comment] 2017-10-16 07:16
Thanks for the excellent report!

I believe this was caused by #46 which I've just partially rewritten and should be fixed by dc4e9b8abf678ce57172d1014a7fa0367926f386

**Closed by jhawthorn** 2017-10-16 07:16 UTC
